DROP TABLE colaborador CASCADE;
DROP TABLE produto CASCADE;
DROP TABLE cliente CASCADE;
DROP TABLE transacao CASCADE;
DROP TABLE pagamento CASCADE;
DROP TABLE venda CASCADE;
DROP TABLE prod_venda CASCADE;
